"""empty message

Revision ID: 257dd74b01c3
Revises: 762402052503
Create Date: 2021-03-16 22:29:30.117587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257dd74b01c3'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('personid', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('personid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
